<div data-reveal-first="" data-slider="slide" role="listitem" class="benefits-cms_list_item w-dyn-item" style="position: relative; display: block; z-index: 1;">
    <div class="benefit-slide">
        <div class="benefit-slide_t">
            <div class="u-48 b-desk"></div>
            <div class="u-272 b-mob"></div>
            <h3 data-scroll-reveal="h" data-slider="h" class="h1 a-center b-desk" style="visibility: visible;" aria-label="Real-Life Location"><span class="split-word" aria-hidden="true"><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">R</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">e</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">a</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">l</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">-</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">L</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">i</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">f</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">e</span></span> <span class="split-word" aria-hidden="true"><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">L</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">o</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">c</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">a</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">t</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">i</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">o</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">n</span></span></h3>
            <div data-scroll-reveal="h" data-slider="h" class="h2 a-center b-mob" style="visibility: visible;" aria-label="Real-Life Location"><span class="split-word" aria-hidden="true"><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">R</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">e</span>
                <span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">a</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">l</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">-</span>
                    <span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">L</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">i</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">f</span>
                        <span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">e</span>
                            </span>
                        <span class="split-word" aria-hidden="true"><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">L</span><span class="split-char" aria-hidden="true"
                            style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">o</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">c</span>
                            <span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">a</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">t</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">i</span>
                                <span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">o</span><span class="split-char" aria-hidden="true" style="translate: none; rotate: none; scale: none; transform: translate(0px); opacity: 1;">n</span></span>
            </div>
            <div class="u-48"></div>
        </div>
        <div class="benefit-slide_c">
            <div class="u-16"></div>
            <div class="benefit-slide_img">
                <div data-scroll-reveal="slide" data-slider="img" class="img-w" style="visibility: visible; clip-path: polygon(0% 0%, 100% 0%, 100% 100%, 0% 100%);"><img src="https://cdn.prod.website-files.com/6a0853d5dab31b18f0677081/6a150affaf1d8cc969d57dd0_img_cam_02.webp" loading="eager" alt="" sizes="100vw" srcset="https://cdn.prod.website-files.com/6a0853d5dab31b18f0677081/6a150affaf1d8cc969d57dd0_img_cam_02-p-500.webp 500w, https://cdn.prod.website-files.com/6a0853d5dab31b18f0677081/6a150affaf1d8cc969d57dd0_img_cam_02-p-800.webp 800w, https://cdn.prod.website-files.com/6a0853d5dab31b18f0677081/6a150affaf1d8cc969d57dd0_img_cam_02-p-1080.webp 1080w, https://cdn.prod.website-files.com/6a0853d5dab31b18f0677081/6a150affaf1d8cc969d57dd0_img_cam_02-p-1600.webp 1600w, https://cdn.prod.website-files.com/6a0853d5dab31b18f0677081/6a150affaf1d8cc969d57dd0_img_cam_02.webp 1920w"
                    class="img" style="translate: none; rotate: none; scale: none; transform: translate(0px);"></div>
            </div>
            <div class="u-16"></div>
        </div>
        <div class="benefit-slide_b">
            <div class="u-48"></div>
            <div class="grid _8-columns">
                <div class="benefit-slide_desc">
                    <p data-scroll-reveal="p" data-slider="p" class="p1 a-center" style="visibility: visible;" aria-label="Nestled between pristine beaches, world-class golf courses and exclusive wellness clubs, Era Residence offers a rare balance of seclusion and seamless access to the finest Mediterranean lifestyle."><span class="split-line-mask" aria-hidden="true" style="text-align: center; overflow: clip;"><span class="split-line" aria-hidden="true" style="text-align: center; translate: none; rotate: none; scale: none; transform: translate(0px);"><span class="split-word" aria-hidden="true">Nestled</span>                        <span class="split-word" aria-hidden="true">between</span> <span class="split-word" aria-hidden="true">pristine</span> <span class="split-word" aria-hidden="true">beaches,</span> <span class="split-word" aria-hidden="true">world-class</span>                        <span class="split-word" aria-hidden="true">golf</span> <span class="split-word" aria-hidden="true">courses</span> <span class="split-word" aria-hidden="true">and</span> <span class="split-word" aria-hidden="true">exclusive</span>
                    <span class="split-word" aria-hidden="true">wellness</span>
                    <span class="split-word" aria-hidden="true">clubs,</span>
                </span>
                        </span><span class="split-line-mask" aria-hidden="true" style="text-align: center; overflow: clip;"><span class="split-line" aria-hidden="true" style="text-align: center; translate: none; rotate: none; scale: none; transform: translate(0px);"><span class="split-word" aria-hidden="true">Era</span>                        <span class="split-word" aria-hidden="true">Residence</span> <span class="split-word" aria-hidden="true">offers</span> <span class="split-word" aria-hidden="true">a</span> <span class="split-word" aria-hidden="true">rare</span>                        <span class="split-word" aria-hidden="true">balance</span> <span class="split-word" aria-hidden="true">of</span> <span class="split-word" aria-hidden="true">seclusion</span> <span class="split-word" aria-hidden="true">and</span>                        <span class="split-word" aria-hidden="true">seamless</span> <span class="split-word" aria-hidden="true">access</span> <span class="split-word" aria-hidden="true">to</span> <span class="split-word" aria-hidden="true">the</span>                        <span class="split-word" aria-hidden="true">finest</span> </span>
                        </span><span class="split-line-mask" aria-hidden="true" style="text-align: center; overflow: clip;"><span class="split-line" aria-hidden="true" style="text-align: center; translate: none; rotate: none; scale: none; transform: translate(0px);"><span class="split-word" aria-hidden="true">Mediterranean</span>                        <span class="split-word" aria-hidden="true">lifestyle.</span></span>
                        </span>
                    </p>
                </div>
            </div>
            <div class="u-48"></div>
            <!-- <div class="grid _8-columns">
                <div class="benefit-slide_cap">
                    <p data-scroll-reveal="p" data-slider="p" class="l1 a-center" style="visibility: visible;" aria-label="Designed as a community, not a complex"><span class="split-line-mask" aria-hidden="true" style="text-align: center; overflow: clip;"><span class="split-line" aria-hidden="true" style="text-align: center; translate: none; rotate: none; scale: none; transform: translate(0px);"><span class="split-word" aria-hidden="true">Designed</span>                        <span class="split-word" aria-hidden="true">as</span> <span class="split-word" aria-hidden="true">a</span> <span class="split-word" aria-hidden="true">community,</span> </span>
                        </span><span class="split-line-mask" aria-hidden="true" style="text-align: center; overflow: clip;"><span class="split-line" aria-hidden="true" style="text-align: center; translate: none; rotate: none; scale: none; transform: translate(0px);"><span class="split-word" aria-hidden="true">not</span>                        <span class="split-word" aria-hidden="true">a</span> <span class="split-word" aria-hidden="true">complex</span></span>
                        </span>
                    </p>
                </div>
            </div> -->
            <div class="u-48"></div>
        </div>
    </div>
</div>